name: junie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      GCP_DOCKER_JUNIE_KEY:
        required: false
    inputs:
      workflow_params:
        description: "JSON string containing all workflow parameters"
        type: string
        required: true

jobs:
  run-junie:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.workflow-params.outputs.checkout_ref }}

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: project-devcontainer
          push: never
          runCmd: |
            pwd
            cd ..
            pwd
            echo "Downloading IDEA..."
            wget -nv https://download.jetbrains.com/idea/ideaIU-2024.3.1.tar.gz -O ideaIU-2024.3.1.tar.gz
            echo "Downloading Junie..."
            wget -nv "https://plugins.jetbrains.com/plugin/download?rel=true&updateId=705220" -O ej.zip
            echo "Extracting IDEA..."
            tar -xzf ideaIU-2024.3.1.tar.gz
            echo "Extracting Junie..."
            unzip ej.zip -d idea-external-plugins
            echo "Running Junie..."
            cd idea-IU-*
            bash ./bin/idea.sh -Didea.platform.prefix=Idea -Djava.awt.headless="true" -Didea.plugins.path="../idea-external-plugins" -Didea.system.path=../idea-logs matterhorn --mode=ElectricJuniorIdea --target="$MATTERHORN_TARGET"
